#!/bin/sh

case "$1" in
  start)
    echo "Loading scull module"
    modprobe scull
    ;;
  stop)
    echo "Unloading scull module"
    rmmod scull
    ;;
  restart)
    $0 stop
    $0 start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
